name: Shell Commands

on: push

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
  

  run-powershell-commands:
    runs-on: windows-latest
    steps:
      - name: directory shell
        run: Get-Location
      - name: working directory
        run: pwd 
        shell: bash

  node-version:
    runs-on: ubuntu-latest
    steps: 
      - name: node version 
        run: node -v 
      - uses: actions/checkout@v2
      - uses: actions/setup-nodev@v1
        with: 
          node-version: 9
      - name: node version
        run: node -v 