name: Shell Commands

on: push

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
  

  run-powershell-commands:
    runs-on: windows-latest
    steps:
      - name: directory shell
        run: Get-Location
      - name: working directory
        run: pwd 
        
